-- Create the 'orders' table
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    table_number integer,
    customer_name text,
    items jsonb NOT NULL,
    total_amount numeric NOT NULL,
    status text NOT NULL CHECK (status IN ('Pending', 'Delivered', 'Paid'))
);

-- Add comments to columns for clarity
COMMENT ON TABLE public.orders IS 'Stores all customer orders for the cafe.';
COMMENT ON COLUMN public.orders.id IS 'Unique identifier for each order.';
COMMENT ON COLUMN public.orders.created_at IS 'Timestamp when the order was created.';
COMMENT ON COLUMN public.orders.table_number IS 'The table number for the order, if applicable.';
COMMENT ON COLUMN public.orders.customer_name IS 'The name of the customer, for takeout or tabs.';
COMMENT ON COLUMN public.orders.items IS 'A JSON array of items in the order, e.g., [{"id": "uuid", "name": "Coffee", "quantity": 1, "price": 3.50}].';
COMMENT ON COLUMN public.orders.total_amount IS 'The calculated total amount for the order.';
COMMENT ON COLUMN public.orders.status IS 'The current status of the order: Pending, Delivered, or Paid.';

-- Enable Row Level Security (RLS) on the 'orders' table
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Create policies for public access.
-- This app uses the public anon key, so RLS policies are set to allow all operations.
-- In a production environment with user authentication, you would create more restrictive policies.

-- Policy to allow all users to view all orders
CREATE POLICY "Allow public read access"
ON public.orders
FOR SELECT
USING (true);

-- Policy to allow all users to create orders
CREATE POLICY "Allow public insert access"
ON public.orders
FOR INSERT
WITH CHECK (true);

-- Policy to allow all users to update orders
CREATE POLICY "Allow public update access"
ON public.orders
FOR UPDATE
USING (true)
WITH CHECK (true);

-- Policy to allow all users to delete orders
CREATE POLICY "Allow public delete access"
ON public.orders
FOR DELETE
USING (true);
